// <auto-generated />
namespace ProjectTeamFour.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class od新增欄位 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(od新增欄位));
        
        string IMigrationMetadata.Id
        {
            get { return "202104010532433_od新增欄位"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
