// <auto-generated />
namespace ProjectTeamFour.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_draft_model_project_and_plan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_draft_model_project_and_plan));
        
        string IMigrationMetadata.Id
        {
            get { return "202103261955233_add_draft_model_project_and_plan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
