// <auto-generated />
namespace ProjectTeamFour.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class edit_Projects_and_Commets_col : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(edit_Projects_and_Commets_col));
        
        string IMigrationMetadata.Id
        {
            get { return "202103120658088_edit_Projects_and_Commets_col"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
